### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by RobloxGithub** [retrouser955/pro-music-bot#4]
The issue with dashboard said error redirect_uri but i added what it said in console: https://81192929.glitch.me/

**Comment by retrouser955** [comment]
can you please provide more information like
1 how to replicate the bug
2 screenshots of the bug
3 a better description of the bug

**Comment by RobloxGithub** [comment]
> can you please provide more information like
> 1 how to replicate the bug
> 2 screenshots of the bug
> 3 a better description of the bug

So basically I set in discord dev portal https://snowflake-dash.glitch.me/auth/login and it didn't work but that what i get in console

**Comment by retrouser955** [comment]
Ah ok. This project was intended for https://replit.com. So, I haven't tested the dashboard out on glitch.
